# Generated by Django 3.0.7 on 2020-06-16 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('uin', models.BigIntegerField()),
            ],
            options={'db_table': 'blacklist',},
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('uin', models.BigIntegerField()),
                ('birth_date', models.DateTimeField()),
            ],
            options={'db_table': 'borrower',},
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'min_sum',
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=56, null=True
                    ),
                ),
                (
                    'max_sum',
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=56, null=True
                    ),
                ),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
            ],
            options={'db_table': 'programs',},
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'sum',
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=56, null=True
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        blank=True,
                        choices=[('failure', 0), ('success', 1)],
                        max_length=191,
                        null=True,
                    ),
                ),
                ('failure_description', models.TextField(blank=True, null=True)),
                (
                    'borrower',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='bank.Borrower',
                    ),
                ),
                (
                    'program',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='bank.Program',
                    ),
                ),
            ],
            options={'db_table': 'applications',},
        ),
    ]
