repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
      args: [--skip-string-normalization]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: debug-statements
    - id: name-tests-test
    - id: check-docstring-first
